openapi: 3.0.1
info:
  title: "API de Produtos Estruturados"
  description: API para consulta de custódia de Produtos estruturados.
  version: 3.1.2.0
servers:
  - url: https://api.btgpactual.com/api-partner-report-extractor
paths:
  /api/v1/report/custody:
    get:
      tags:
        - get-partner-report-custody
      summary: Busca relatório de Custódias por parceiro
      description: |
        Endpoint responsável pela busca de informações de Relatório de Custódias em **D0**.

        Pelo fato da chamada ser assíncrona, o retorno se dará via **Webhook**, que pode ser cadastrado pelo próprio portal do desenvolvedor em **Webhooks > Manutenção > Botão Cadastrar Webhook**, com nome de **Relatório de Custodia Por Parceiro (partner-report-custodia)**. 

        Sua documentação pode ser encontrada na página de Webhook. 

        Caso o webhook não esteja cadastrado, será emitido um erro de forma síncrona com a seguinte mensagem:

        `Webhook not registered for partner cnpj [{CNPJ}], cge [{CGE}].`

        **Uma vez solicitado, os dados informados permanecerão estáticos até a próxima atualização a partir das 8h am.**

        ---
        **Características:**

        Tipo de chamada: Assíncrona

        Limite de requisições: 60 por minuto

        Frequência de atualização: 1 vez ao dia

        Janela de dados: N/A *(Não se Aplica)*
      operationId: getCustodia
      parameters:
        - name: x-id-partner-request
          description: |
            UUID gerado randômicamente, usado para identificador cada request efetuado. 
            Sempre utilizar um diferente para cada requisição, mesmo que sejam os mesmos parâmetros.

            *Exemplo:* `5607cd68-3231-4eb7-a1f9-ed3ff854b1af`
          schema:
            type: string
          in: header
          required: true
        - name: access_token
          description: |
            Token de acesso para a API, esse deve ser gerado usando OAuth2 e Grant Type do tipo Client Credentials.
            As credenciais podem ser obtidas pelo portal do desenvolvedor.

            *Exemplo:* `eyJ0eXAiOMNSBHDBDxhUnman9u.eyJ0abdhb2F1jkGfrnmkmGFj.eyJ0sadsadsadas`
          schema:
            type: string
          in: header
          required: true
      responses:
        "202":
          description: Requisição enviada com sucesso.
          headers:
            x-id-pactual:
              description: Id pactual da operação
              style: simple
              schema:
                type: string
        "401":
          description: Requisição não autorizado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseError"
        "403":
          description: Erro no body da requisição
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseError"
  /api/v1/report/custody-by-date:
    post:
      tags:
        - post-partner-report-custody-by-date
      summary: Busca relatório de Custódias por parceiro e data
      description: |
        Endpoint responsável pela busca de informações de Relatório de Custódias na data informada.

        Pelo fato da chamada ser assíncrona, o retorno se dará via **Webhook**, que pode ser cadastrado pelo próprio portal do desenvolvedor em **Webhooks > Manutenção > Botão Cadastrar Webhook**, com nome de **Relatório de Custodia Por Parceiro e data (partner-report-custodia-by-date)**. 

        Sua documentação pode ser encontrada na página de Webhook. 

        Caso o webhook não esteja cadastrado, será emitido um erro de forma síncrona com a seguinte mensagem:

        `Webhook not registered for partner cnpj [{CNPJ}], cge [{CGE}].`

        **Uma vez solicitado, os dados informados permanecerão estáticos até a próxima atualização a partir das 8h am.**

        ---
        **Características:**

        Tipo de chamada: Assíncrona

        Limite de requisições: 60 por minuto

        Frequência de atualização: 1 vez ao dia

        Janela de dados: N/A *(Não se Aplica)*
      operationId: getCustodiaByDate
      parameters:
        - name: x-id-partner-request
          description: |
            UUID gerado randômicamente, usado para identificador cada request efetuado. 
            Sempre utilizar um diferente para cada requisição, mesmo que sejam os mesmos parâmetros.

            *Exemplo:* `5607cd68-3231-4eb7-a1f9-ed3ff854b1af`
          schema:
            type: string
          in: header
          required: true
        - name: access_token
          description: |
            Token de acesso para a API, esse deve ser gerado usando OAuth2 e Grant Type do tipo Client Credentials.
            As credenciais podem ser obtidas pelo portal do desenvolvedor.

            *Exemplo:* `eyJ0eXAiOMNSBHDBDxhUnman9u.eyJ0abdhb2F1jkGfrnmkmGFj.eyJ0sadsadsadas`
          schema:
            type: string
          in: header
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ReportExtractorRequest"
      responses:
        "202":
          description: Requisição enviada com sucesso.
          headers:
            x-id-pactual:
              description: Id pactual da operação
              style: simple
              schema:
                type: string
        "401":
          description: Requisição não autorizado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseError"
        "403":
          description: Erro no body da requisição
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseError"
components:
  schemas:
    Error:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
    ErrorMetadata:
      type: object
      properties:
        globalErrors:
          type: array
          items:
            $ref: "#/components/schemas/Error"
        fieldErrors:
          type: object
          additionalProperties:
            type: object
    ResponseError:
      type: object
      properties:
        status:
          type: integer
          format: int32
        title:
          type: string
        meta:
          $ref: "#/components/schemas/ErrorMetadata"
    ReportExtractorRequest:
      description: Requisição para busca de Custódias por data.
      type: object
      properties:
        refDate:
          description: Data referência da consulta.
          type: string
          example: "2023-07-28"
