version: 0.2

phases:
  install:
    commands:
      - pip install aws-sam-cli

  build:
    commands:
      - sam build --template-file agf-data-pipeline/template.yaml

post_build:
  commands:
    - |
      sam deploy \
        --template-file .aws-sam/build/template.yaml \
        --stack-name agfi-lambda-dev \
        --s3-bucket agfi-pipeline-artifactbucket-o3htnl0pnv5u \
        --no-confirm-changeset \
        --no-fail-on-empty-changeset \
        --capabilities CAPABILITY_NAMED_IAM